### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by soniamartinot** [boschresearch/Hyp-OW#1]
The link to download your annotations of pascal does not work: gdown https://drive.google.com/uc?id=1paoJRaHTnptPaEJd3D6XiUkNetLgti6R

**Comment by tldoan** [comment]
Hi,

Thank you for pointing this broken link. No idea where this link does not work anymore but I believe you can find the file from the official coco website (https://cocodataset.org/#download).
Hope it helps.

Best,
Thang,
